### ISSUE TITLE
what the definition of self.m3

### ISSUE THREAD

**Issue by mxer** [niliusha123/SubCenterArcFace-sphereface2#1]
Hi, I can't find the definition of self.m3 in
https://github.com/niliusha123/SubCenterArcFace/blob/098d7efe1627c088ca6164f03c2e2e310d243693/metrics.py#L43

**Comment by niliusha123** [comment]
Sorry,my wrong,
in fact , according to the paper，you could delete it directly，it is just my experimental parameters. I forget to delete it.
or you could set it in __init__() by yourself to check whether this margin is helpful to your experiment
